<div class="home-banner-main-slick">
    <div>
        <a href="<?= $block->getUrl('roupas.html') ?>">
            <img src="<?= $this->getViewFileUrl('images/banner-main/1.png'); ?>" alt="banner noryn"/>
        </a>
    </div>
    <div>
        <a href="<?= $block->getUrl('acessorios.html') ?>">
            <img src="<?= $this->getViewFileUrl('images/banner-main/3.png'); ?>" alt="banner noryn"/>
        </a>
    </div>
    <div>
        <a href="<?= $block->getUrl('bolsas.html') ?>">
            <img src="<?= $this->getViewFileUrl('images/banner-main/2.png'); ?>" alt="banner noryn"/>
        </a>
    </div>
</div>
