<div class="home-banner-categories">

    <div class="categories-box">
        <h3><?= __('Clothes') ?>
            <small><?= __('Fashion that reveals your identity') ?></small>
        </h3>
        <img src="<?= $this->getViewFileUrl('images/categories/1.png'); ?>" alt="banner noryn"/>
        <div class="box-action">
            <a href="<?= $block->getUrl('roupas.html') ?>"><?= __('See more') ?></a>
        </div>
    </div>

    <div class="categories-box">
        <h3><?= __('Accessories') ?>
            <small><?= __('Details that make all the difference') ?></small>
        </h3>
        <img src="<?= $this->getViewFileUrl('images/categories/2.png'); ?>" alt="banner noryn"/>
        <div class="box-action">
            <a href="<?= $block->getUrl('acessorios.html') ?>"><?= __('See more') ?></a>
        </div>
    </div>

    <div class="categories-box">
        <h3><?= __('Shoes') ?>
            <small><?= __('Comfort and style at every step') ?></small>
        </h3>
        <img src="<?= $this->getViewFileUrl('images/categories/3.png'); ?>" alt="banner noryn"/>
        <div class="box-action">
            <a href="<?= $block->getUrl('calcados.html') ?>"><?= __('See more') ?></a>
        </div>
    </div>

    <div class="categories-box">
        <h3><?= __('Scholarships') ?>
            <small> <?= __('Functionality with personality') ?></small>
        </h3>
        <img src="<?= $this->getViewFileUrl('images/categories/4.png'); ?>" alt="banner noryn" />
        <div class="box-action">
            <a href="<?= $block->getUrl('bolsas.html') ?>"><?= __('See more') ?></a>
        </div>
    </div>

</div>
