<div class="home-how-it-works">

    <h2><?= __('How does it work?') ?></h2>

    <div class="row">
        <div class="col">
            <div class="box-icon">
                <i class="fa-solid fa-truck-fast"></i>
            </div>
            <h3><?= __('Fast Delivery') ?></h3>
            <p><?= __('Receive your order quickly and safely, directly at your address.') ?></p>
        </div>

        <div class="col">
            <div class="box-icon">
                <i class="fa-solid fa-user-shield"></i>
            </div>
            <h3><?= __('Secure Payment') ?></h3>
            <p><?= __('We use the main gateways with advanced encryption.') ?></p>
        </div>

        <div class="col">
            <div class="box-icon">
                <i class="fa-solid fa-shop-lock"></i>
            </div>
            <h3><?= __('Buy safely') ?></h3>
            <p><?= __('Choose the payment method that is most convenient for you.') ?></p>
        </div>

        <div class="col">
            <div class="box-icon">
                <i class="fa-solid fa-house-circle-check"></i>
            </div>
            <h3><?= __('Receive at home') ?></h3>
            <p><?= __('Your order will be delivered carefully, on time and with the standard of excellence that we value.') ?></p>
        </div>

    </div>
</div>
